org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=true

minecraft_version=1.21.1
loader_version=0.19.5
loom_version=1.18-SNAPSHOT

version=0.1.0
group=com.eternalerkle.speedrun

fabric_api_version=0.116.17+1.21.1
fantasy_version=0.6.4+1.21
polymer_version=0.9.19+1.21.1
permissions_api_version=0.3.3
junit_version=5.11.4
